solution: solution.cc
	g++ --std=c++20 -g -O0 -I /opt/homebrew/Cellar/googletest/1.17.0/include -L /opt/homebrew/Cellar/googletest/1.17.0/lib -fsanitize=address -fsanitize=undefined -l gtest -l gtest_main -o solution solution.cc
